### ISSUE TITLE
Updating from 0.1.0 to @latest breaks modal switcher.

### ISSUE THREAD

**Issue by vybu** [sebinsua/react-redux-simple-modal#3]
As far as I am aware there shouldn't be any changes to how modal switcher is used when going from version 0.1.0 to 0.2.4. However for us modal switcher stops working. It seems that ModalSwitcher doesn't get **modals** as prop. Therefore it's undefined and it tries to access undefined[modalType].

**Comment by sebinsua** [comment]
I am not sure why this would happen.

[These tests are passing.](https://github.com/sebinsua/react-redux-simple-modal/blob/master/src/ModalSwitcher.spec.js#L50-L62)

Could you `git clone` the repo and run `npm install && npm test` to check that they pass for you?

**Comment by vybu** [comment]
Unfortunately can't run tests, due to failing flow server on my machine.

**Comment by sebinsua** [comment]
Remove `flow && ` from [this line](https://github.com/sebinsua/react-redux-simple-modal/blob/master/package.json#L20), and run `npm test` again.

**Comment by sebinsua** [comment]
Closing this until you can demonstrate that there is a bug...
